server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Soholight
    username: root
    password: 990816
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
      init:
        mode: always
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
